GuideLines/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('guides.urls'))
]

if settings.DEBUG:
    # urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guides/urls.py
from django.urls import path

from .views import RegistrationView, HomePageView, NewGuideView, DetailGuideView, UpdateGuideView, DeleteGuideView, \
    NewArticleView, DetailArticleView, UpdateArticleView, DeleteArticleView, publish_article, do_not_publish_article


app_name = 'guides'
urlpatterns = [
    path('registrations/registration/', RegistrationView.as_view(), name='registration'),
    path('guides/new/', NewGuideView.as_view(), name='new_guide'),
    path('guides/<int:guide_pk>/', DetailGuideView.as_view(), name='detail_guide'),
    path('guides/<int:guide_pk>/edit/', UpdateGuideView.as_view(), name='edit_guide'),
    path('guides/<int:guide_pk>/delete/', DeleteGuideView.as_view(), name='delete_guide'),
    path('guides/<int:guide_pk>/articles/new/', NewArticleView.as_view(), name='new_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/', DetailArticleView.as_view(), name='detail_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/edit/', UpdateArticleView.as_view(), name='edit_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/delete/', DeleteArticleView.as_view(), name='delete_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/publish/', publish_article, name='publish_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/do_not_publish/', do_not_publish_article,
         name='do_not_publish_article'),
    path('', HomePageView.as_view(), name='home_page'),
]

templates/base.html
{% extends 'bootstrap5/bootstrap5.html' %}

{% load static %}
{% load bootstrap5 %}

{% block bootstrap5_title %}{% block title %}Главная{% endblock %} - GuideLines{% endblock %}

{% block bootstrap5_content %}
<div class="container-fluid">
    <div class="row bg-light">
        <div class="col-12">
            <div class="container">
                <div id="header" class="navbar navbar-light navbar-expand-md bg-light">
                    <div class="container-fluid position-relative">

                        <span class="navbar-brand mb-0 h1 d-md-inline d-none">GuideLines</span>

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarNav">
                            <div class="navbar-nav me-auto mb-1 mb-md-0">
                                <a class="nav-link active" aria-current="page" href="#">Руководства</a>
                                <a class="nav-link" href="#">Авторы</a>
                            </div>
                        </div>

                        <div class="position-absolute end-0 top-0 me-2 mt-0 d-flex align-items-center">
                            {% if user.is_authenticated %}
                                <span class="navbar-text me-2 ">
                                    {% if user.first_name %}
                                        {{ user.first_name }} {{ user.last_name }}
                                    {% else %}
                                        {{ user.username }}
                                    {% endif %}
                                </span>
                                <a class="btn btn-outline-secondary" href="{% url 'logout' %}" id="logout-btn">Выход</a>
                            {% else %}
                                <a class="btn btn-outline-primary" href="{% url 'login' %}" id="login-btn">Вход</a>
                            {% endif %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="content" class="container pt-4">
    {% block content %}

    {% endblock %}
    </div>
</div>


<script src="{% static 'js/jquery-3.6.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>
{% endblock %}

templates/main.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% load static %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <a href="{% url 'guides:new_guide' %}">
            {% bootstrap_button content='Новое Руководство' name='new_guide_btn'%}
        </a>
    {% endif %}

<div class="row mb-5 row-cols-xl-4 row-cols-lg-3 row-cols-md-2 row-cols-1 g-4" id="guides">
    {% for guide in guides %}
    <div class="col">
        <a href="{% url 'guides:detail_guide' guide_pk=guide.pk %}"
           id="id_guide_{{ guide.pk }}"
           class="btn w-100 p-0">
            <div class="card bg-dark text-light text-start" >
                {% if guide.cover %}
                    <img src="{{ guide.cover.url }}" class="card-img" alt="">
                {% else %}
                    <img src="{% static 'img/default-guide-cover.jpg' %}" class="card-img" alt="">
                {% endif %}


                <div class="card-body">
                    <h2 class="h3 card-title mb-4">{{ guide.name }}</h2>
                    <p class="card-text">{{ guide.description }}</p>
                </div>
                <div class="card-footer border-light">
                    <p class="card-text text-end ">{{ guide.author.first_name }} {{ guide.author.last_name }}</p>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}