GuideLines/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('guides.urls'))
]

if settings.DEBUG:
    # urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guides/urls.py
from django.urls import path

from .views import RegistrationView, HomePageView, NewGuideView, DetailGuideView, UpdateGuideView, DeleteGuideView, \
    NewArticleView, DetailArticleView, UpdateArticleView, DeleteArticleView, publish_article, do_not_publish_article


app_name = 'guides'
urlpatterns = [
    path('registrations/registration/', RegistrationView.as_view(), name='registration'),
    path('guides/new/', NewGuideView.as_view(), name='new_guide'),
    path('guides/<int:guide_pk>/', DetailGuideView.as_view(), name='detail_guide'),
    path('guides/<int:guide_pk>/edit/', UpdateGuideView.as_view(), name='edit_guide'),
    path('guides/<int:guide_pk>/delete/', DeleteGuideView.as_view(), name='delete_guide'),
    path('guides/<int:guide_pk>/articles/new/', NewArticleView.as_view(), name='new_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/', DetailArticleView.as_view(), name='detail_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/edit/', UpdateArticleView.as_view(), name='edit_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/delete/', DeleteArticleView.as_view(), name='delete_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/publish/', publish_article, name='publish_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/do_not_publish/', do_not_publish_article,
         name='do_not_publish_article'),
    path('', HomePageView.as_view(), name='home_page'),
]

guides/models.py
from datetime import datetime
from os.path import splitext
import os
from pathlib import Path
from shutil import rmtree

from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import pre_delete
from django.dispatch import receiver


def _upload_path(instance, filename):
    return instance.get_upload_path(filename)


class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to=_upload_path,
                               null=True,
                               blank=True,
                               verbose_name='Аватар')

    def get_upload_path(self, filename):
        return str(self.username) + "/" \
               + splitext(filename)[0] + '_' + str(datetime.now().timestamp()) + splitext(filename)[1]

    REQUIRED_FIELDS = ['first_name', 'last_name']


class Guide(models.Model):
    """Модель Руководства"""

    name = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')
    cover = models.ImageField(upload_to=_upload_path,
                              null=True,
                              blank=True,
                              verbose_name='Обложка')
    author = models.ForeignKey(CustomUser, on_delete=models.PROTECT,
                               verbose_name='Автор')

    def get_upload_path(self, filename):
        return str(self.author.username) + '/' \
               + splitext(filename)[0] + '_' + str(datetime.now().timestamp()) + splitext(filename)[1]

    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Гайд'
        verbose_name_plural = 'Гайды'


class Article(models.Model):
    """Модель статьи"""

    name = models.CharField(max_length=200, verbose_name='Название')
    text = models.TextField(null=True, blank=True, verbose_name='Текст')

    guide = models.ForeignKey(Guide, on_delete=models.PROTECT,
                              verbose_name='Руководство')
    author = models.ForeignKey(CustomUser, on_delete=models.PROTECT,
                               verbose_name='Автор')
    draft = models.BooleanField(default=True, verbose_name='Черновик')

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    REQUIRED_FIELDS = ['name']


@receiver(pre_delete, sender=CustomUser)
def delete_user_root_dir(sender, instance, **kwargs):
    username = instance.username
    if os.path.exists(settings.MEDIA_ROOT / username):
        rmtree(settings.MEDIA_ROOT / username, ignore_errors=True)

guides/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Guide, Article


class UpdateArticleForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update(rows='4')

    class Meta:
        model = Article
        fields = ['name', 'text']


class CreationArticleForm(ModelForm):

    class Meta:
        model = Article
        fields = ['name', 'text']


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'avatar')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'avatar')


class CreationGuideForm(ModelForm):

    class Meta:
        model = Guide
        fields = ['name', 'description', 'cover']


class UpdateGuideForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].widget.attrs.update(rows='4')

    class Meta:
        model = Guide
        fields = ['name', 'description', 'cover']

guides/views.py
from abc import ABC
from django.db.models import QuerySet
from django.http import HttpResponse, HttpRequest
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.urls import reverse_lazy


from .forms import CustomUserCreationForm, CreationGuideForm, UpdateGuideForm, CreationArticleForm, UpdateArticleForm
from .models import Guide, Article


def do_not_publish_article(request: HttpRequest, guide_pk: int, pk: int) -> HttpResponse:
    """Снимает Статью с публикации"""
    article = Article.objects.get(pk=pk)
    article.draft = True
    article.save()
    return redirect('guides:detail_guide', guide_pk=guide_pk)


def publish_article(request: HttpRequest, guide_pk: int, pk: int) -> HttpResponse:
    """Публикует Статью"""
    article = Article.objects.get(pk=pk)
    article.draft = False
    article.save()
    return redirect('guides:detail_guide', guide_pk=guide_pk)


class DeleteArticleView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Удаление Руководства"""
    model = Article
    login_url = reverse_lazy('login')

    def get_success_url(self):
        return reverse_lazy('guides:detail_guide', kwargs={'guide_pk': self.object.guide.pk})

    def test_func(self):
        return self.get_object().author == self.request.user


class UpdateArticleView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Обновление (редактирование) Статьи"""
    model = Article
    form_class = UpdateArticleForm
    template_name = 'article/edit.html'
    login_url = reverse_lazy('login')

    def get_queryset(self):
        return Article.objects.select_related('guide', 'author').filter(pk=self.kwargs.get('pk'))

    def get_success_url(self):
        return reverse_lazy('guides:detail_article', kwargs={'guide_pk': self.object.guide.pk,
                                                             'pk': self.object.pk})

    def test_func(self):
        return self.get_object().author == self.request.user


class DetailArticleView(UserPassesTestMixin, DetailView):
    """Детальный просмотр Статьи"""
    model = Article
    context_object_name = 'article'
    template_name = 'article/detail.html'

    def get_queryset(self):
        return Article.objects.select_related('guide', 'author').filter(pk=self.kwargs.get('pk'))

    def test_func(self):
        article: Article = self.get_object()
        if article.draft:
            if not self.request.user.is_authenticated:
                return False
            if self.request.user == article.author:
                return True
            return False
        else:
            return True


class NewArticleView(LoginRequiredMixin, CreateView):
    """Создание новой Статьи"""
    form_class = CreationArticleForm
    template_name = 'article/new.html'
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        """добавить автора и Руководство перед сохранением, если форма валидна"""
        form.instance.author = self.request.user
        form.instance.guide = Guide.objects.get(pk=self.kwargs.get('guide_pk'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('guides:detail_guide', kwargs={'guide_pk': self.kwargs.get('guide_pk')})


class DeleteGuideView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Удаление Руководства"""
    model = Guide
    success_url = reverse_lazy('guides:home_page')
    login_url = reverse_lazy('login')
    slug_field = 'pk'
    slug_url_kwarg = 'guide_pk'

    def test_func(self):
        return self.get_object().author == self.request.user


class UpdateGuideView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Обновление (редактирование) Руководства"""

    model = Guide
    form_class = UpdateGuideForm
    template_name = 'guide/edit.html'
    login_url = reverse_lazy('login')
    slug_field = 'pk'
    slug_url_kwarg = 'guide_pk'

    def get_queryset(self):
        return Guide.objects.select_related('author').filter(pk=self.kwargs.get('guide_pk'))

    def get_success_url(self):
        return reverse_lazy('guides:detail_guide', kwargs={'guide_pk': self.object.pk})

    def test_func(self):
        return self.get_object().author == self.request.user


class RegistrationView(CreateView):
    """Регистрация пользователя"""
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('guides:home_page')
    template_name = 'registration/registration.html'


class HomePageView(TemplateView):
    """Главная страница"""
    template_name = 'main.html'

    def get_context_data(self, **kwargs):
        """Добавляет Руководства в контекст страницы"""
        context = super().get_context_data(**kwargs)
        # context['guides'] = Guide.objects.all()
        context['guides'] = Guide.objects.select_related('author').all()
        return context


class NewGuideView(LoginRequiredMixin, CreateView):
    """Создание нового Руководства"""
    login_url = reverse_lazy('login')
    form_class = CreationGuideForm
    template_name = 'guide/new.html'

    def form_valid(self, form):
        """добавить автора перед сохранение, если форма валидна"""
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('guides:detail_guide', kwargs={'guide_pk': self.object.pk})


class DetailGuideView(DetailView):
    """Детальный просмотр поста"""
    model = Guide
    context_object_name = 'guide'
    template_name = 'guide/detail.html'
    slug_field = 'pk'
    slug_url_kwarg = 'guide_pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not self.request.user.is_authenticated:
            q = Q(draft=False)
        else:
            q = Q(draft=False) | Q(author=self.request.user)
        # articles = self.object.article_set.filter(q)
        articles = self.object.article_set.select_related('guide', 'author').filter(q)
        # articles = Article.objects.select_related('guide', 'author').filter(Q(guide=self.object) & q)
        context['articles'] = articles
        return context


def delete_article_view(request):
    """Заглушка"""
    pass

templates/guide/detail.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% load static %}
{#{% load filters %}#}

{% block title %}
    {{ guide.name }}
{% endblock %}

{% block content %}
<div class="row justify-content-center pt-5 mb-5">
    <div class="col">

        <div class="card bg-dark text-light"  id="guide">
            {% if guide.cover %}
                <img src="{{ guide.cover.url }}" class="card-img" alt="">
            {% else %}
                <img src="{% static 'img/default-guide-cover.jpg' %}" class="card-img" alt="">
            {% endif %}
            <div class="card-body py-4">
                {% if guide.author == user %}
                    <div class="dropdown">
                        <a href="#" class="btn rounded-circle text-light my-4 mx-3 p-2" id="id_guide_menu_btn" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="24" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
                              <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                            </svg>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="guide_menu_btn" id="id_guide_menu">
                            <li><a class="dropdown-item" href="{% url 'guides:edit_guide' guide_pk=guide.pk%}" id="id_edit_guide_btn">Редактировать</a></li>
                            <li><a class="dropdown-item text-danger" href="#" id="id_delete_guide_btn" data-bs-toggle="modal" data-bs-target="#id_modal_delete_panel">Удалить</a></li>
                        </ul>
                    </div>
                {% endif %}
                <h1 class="card-title mb-5">{{ guide.name }}</h1>
                <p class="card-text">{{ guide.description }}</p>
            </div>
            <div class="card-footer border-light py-3">
                <p class="card-text text-end ">{{ guide.author.first_name }} {{ guide.author.last_name }}</p>
            </div>
        </div>

    </div>
</div>

<div class="row mb-5 row-cols-xl-4 row-cols-lg-3 row-cols-md-2 row-cols-1 g-4" id="articles">
    {% for article in articles %}
    <div class="col">
        <a href="{% url 'guides:detail_article' guide_pk=guide.pk pk=article.pk%}"
           id="id_article_{{ article.pk }}"
           class="btn w-100 p-0">
            <div class="card bg-dark text-light text-start" >
                <div class="card-body">
                    <h2 class="card-title mb-5">{{ article.name }}</h2>
                    <p class="card-text">{{ article.text }}</p>
                </div>
                <div class="card-footer border-light row">
                    {% if article.draft %}
                        <p class="text-warning text-start col mb-0">Черновик</p>
                    {% endif %}
                    <p class="text-end col mb-0">{{ article.author.first_name }} {{ article.author.last_name }}</p>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
    {% if user.is_authenticated %}
    <div class="col">
        <a href="{% url 'guides:new_article' guide_pk=guide.pk %}"
           id="id_new_article_btn"
           class="btn w-100 p-0"
           data-bs-toggle="tooltip"
           data-bs-placement="top"
           title="Добавить Статью">
            <div class="card" >
                <div class="card-body d-flex justify-content-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-plus align-self-center" viewBox="0 0 16 16">
                      <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                    </svg>
                </div>
            </div>
        </a>
    </div>
    {% endif %}
</div>

    <!-- Modal -->
{% if guide.author == user %}
<div class="modal fade" id="id_modal_delete_panel" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Удаление руководства</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <p>Вы точно хотите удалить: <span class="fw-bold">{{ guide.name }}</span>?</p>
          <p>Восстановлени будет невозможно</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
        <form method="POST" action="{% url "guides:delete_guide" guide_pk=guide.pk %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" id="id_confirm_delete_guide_btn" >Удалить</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

templates/guide/edit.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% load static %}

{% block title %}
    Редактировать
{% endblock %}

{% block content %}
<div class="row justify-content-center pt-5 mb-5">
    <div class="col">
        <div class="card bg-dark text-light"  id="guide">
            {% if guide.cover %}
                <img src="{{ guide.cover.url }}" class="card-img" alt="">
            {% else %}
                <img src="{% static 'img/default-guide-cover.jpg' %}" class="card-img" alt="">
            {% endif %}
            <div class="card-body py-4">
                <form method="post" class="form pt-2" enctype="multipart/form-data">
                <div class="card-body py-4">

                    {% csrf_token %}
                    {% bootstrap_field  form.name layout='horizontal' show_label='skip' size='medium' field_class='col-md-9 col-10'%}
                    {% bootstrap_field  form.description layout='horizontal' show_label='skip' size='medium' field_class='col pt-3'%}
                    {% bootstrap_field  form.cover layout='horizontal' show_label='skip' size='medium' field_class='col pt-3'%}

                </div>
                <div class="card-footer border-light py-3">
                    {% buttons %}
                        <button type="submit" class="btn btn-primary float-start">Сохранить</button>
                    {% endbuttons %}
                    <p class="card-text text-end ">{{ guide.author.first_name }} {{ guide.author.last_name }}</p>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/guide/new.html
{% extends 'base.html' %}

{% load bootstrap5 %}

{% block title %}
    Новое Руководство
{% endblock %}

{% block content %}
<div class="row justify-content-center pt-5">
    <div class="col-md-8">
        <form method="post" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form show_label='skip' field_class='mb-4' layout='horizontal'%}
            <div class="row mt-4">

            {% buttons %}
                <button type="submit" class="btn btn-primary float-end">Создать Руководство</button>
            {% endbuttons %}
            </div>
        </form>
    </div>
</div>
{% endblock %}