GuideLines/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import never_cache
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('guides.urls'))
]

if settings.DEBUG:
    # urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guides/urls.py
from django.urls import path

from .views import RegistrationView, HomePageView, NewGuideView, DetailGuideView, UpdateGuideView, DeleteGuideView, \
    NewArticleView, DetailArticleView, UpdateArticleView, DeleteArticleView, publish_article, do_not_publish_article


app_name = 'guides'
urlpatterns = [
    path('registrations/registration/', RegistrationView.as_view(), name='registration'),
    path('guides/new/', NewGuideView.as_view(), name='new_guide'),
    path('guides/<int:guide_pk>/', DetailGuideView.as_view(), name='detail_guide'),
    path('guides/<int:guide_pk>/edit/', UpdateGuideView.as_view(), name='edit_guide'),
    path('guides/<int:guide_pk>/delete/', DeleteGuideView.as_view(), name='delete_guide'),
    path('guides/<int:guide_pk>/articles/new/', NewArticleView.as_view(), name='new_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/', DetailArticleView.as_view(), name='detail_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/edit/', UpdateArticleView.as_view(), name='edit_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/delete/', DeleteArticleView.as_view(), name='delete_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/publish/', publish_article, name='publish_article'),
    path('guides/<int:guide_pk>/articles/<int:pk>/do_not_publish/', do_not_publish_article,
         name='do_not_publish_article'),
    path('', HomePageView.as_view(), name='home_page'),
]

templates/article/detail.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% load static %}

{% block title %}
    {{ article.name }}
{% endblock %}

{% block content %}
    <article id="article" class="container">
        <div class="row title bg-white border mb-4">
            {% if article.draft %}
                <div class="p-2 col-md-2 col-3 ">
                    <span class="w-100 h-100 text-center text-danger border border-danger d-block py-2">Черновик</span>
                </div>
            {% endif %}

            <h2 class="text-center col-md-8 col-6 py-2">{{ article.name }}</h2>

            {% if article.author == user %}
            <div class="dropdown w-auto">
                <a href="#" class="btn rounded-circle text-dark my-2 mx-1 p-1" id="id_article_menu_btn" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" width="26" height="24" fill="currentColor" class="bi bi-three-dots" viewBox="0 0 16 16">
                      <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"/>
                    </svg>
                </a>
                <ul class="dropdown-menu" aria-labelledby="article_menu_btn" id="id_article_menu">
                    <li><a class="dropdown-item" href="{% url 'guides:edit_article' guide_pk=article.guide.pk pk=article.pk %}" id="id_edit_article_btn">Редактировать</a></li>
                    <li><a class="dropdown-item text-danger" href="#" id="id_delete_article_btn" data-bs-toggle="modal" data-bs-target="#id_modal_delete_panel">Удалить</a></li>
                </ul>
            </div>
        </div>
        {% endif %}

        <div class="row bg-white border mb-5">
            <div class="col">
                <p class="text pt-3">{{ article.text }}</p>
            </div>
        </div>
    </article>

    {% if article.draft %}
        <a class="btn btn-outline-primary" href="{% url 'guides:publish_article' guide_pk=article.guide.pk pk=article.pk %}" id="id_publish_btn">Опубликовать Статью</a>
    {% else %}
        {% if user.is_authenticated and user == article.author%}
            <a class="btn btn-outline-secondary" href="{% url 'guides:do_not_publish_article' guide_pk=article.guide.pk pk=article.pk %}" id="id_make_draft_btn">Сделать черновиком</a>
        {% endif %}
    {% endif %}

     <!-- Modal -->
{% if article.author == user %}
<div class="modal fade" id="id_modal_delete_panel" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Удаление Статьи</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <p>Вы точно хотите удалить: <span class="fw-bold">{{ article.name }}</span>?</p>
          <p>Восстановлени будет невозможно</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
        <form method="POST" action="{% url "guides:delete_article" guide_pk=article.guide.pk pk=article.pk %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" id="id_confirm_delete_article_btn" >Удалить</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

templates/article/edit.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% load static %}

{% block title %}
    Редактировать
{% endblock %}

{% block content %}

<div class="row justify-content-center pt-5">
    <div class="col-md-8">
        <form method="post" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form show_label='skip' field_class='mb-4' layout='horizontal'%}
            <div class="row mt-4">

            {% buttons %}
                <button type="submit" class="btn btn-primary float-end">Сохранить Статью</button>
            {% endbuttons %}
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/article/new.html
{% extends 'base.html' %}

{% load bootstrap5 %}

{% block title %}
    Новая статья
{% endblock %}

{% block content %}
<div class="row justify-content-center pt-5">
    <div class="col-md-8">
        <form method="post" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form show_label='skip' field_class='mb-4' layout='horizontal'%}
            <div class="row mt-4">

            {% buttons %}
                <button type="submit" class="btn btn-primary float-end">Создать Статью</button>
            {% endbuttons %}
            </div>
        </form>
    </div>
</div>
{% endblock %}